import { test } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const run=promisify(execFile),dist=fileURLToPath(new URL('../dist/',import.meta.url)),session=`passport-stats-controls-${process.pid}`;
const output=fileURLToPath(new URL('../output/playwright/',import.meta.url));
const counters={playSeconds:7320,blocksBroken:12,blocksPlaced:4,damageTakenMilli:125500,deaths:2,mobKills:4,playerKills:1,distanceCm:456700};
const future=new Date(Date.now()+86400000).toISOString();
const subjectId='00000000-0000-4000-8000-000000000001';
const serverRecord=(id,label,statisticsEnabled)=>({id,label,commandName:id==='lobby'?'로비':id==='survival'?'야생':id,statisticsEnabled,enabled:true,sensitive:false,accessMode:'members',discordRequirement:'any',allowedSubjectIds:[],updatedAt:'2026-10-02T00:00:00.000Z',createdAt:'2026-10-01T00:00:00.000Z',online:true,proxyAvailable:true,paperSeenAt:future});
let state;
const reset=()=>{state={role:'owner',servers:[serverRecord('lobby','합성 로비',false),serverRecord('survival','합성 야생',true)],writes:[],previews:[],revision:1,resetError:null,serverError:null,cleared:false,exports:[],queries:[],queryPaths:[],membershipFixtures:false,holdStats:false,releaseStats:null,holdExport:false,releaseExport:null,manual:{title:'이용 안내',notionUrl:null,embedUrl:null,configured:false,updatedAt:null,revision:0},manualWrites:[],manualConflict:false,credentials:[],credentialWrites:[]};};
const server=http.createServer(async(req,res)=>{
 const url=new URL(req.url,'http://127.0.0.1'),p=url.pathname;
 const json=(code,data)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 const body=async()=>{let value='';for await(const part of req)value+=part;return value?JSON.parse(value):{};};
 if(p==='/v1/auth/session')return json(200,{authenticated:true,csrfToken:'synthetic-csrf',authMode:'university'});
 if(p==='/v1/admin/session')return json(200,{authenticated:true,schoolVerified:true,subjectId:'owner',displayName:'합성 운영자',enrolled:true,enrollmentPending:false,bootstrapAvailable:false,mfaRequired:false,authorized:true,role:state.role,permissions:{read:true,write:state.role!=='viewer',manageOperators:state.role==='owner'},mfaVerified:false,mfaVerifiedUntil:null});
 if(p==='/v1/admin/overview')return json(200,{subjects:1,linked:1,suspended:0,snapshot:null,sync:{enabled:false,running:false,lastSuccessAt:null,lastError:null},servers:state.servers});
 if(p==='/v1/admin/servers')return json(200,{servers:state.servers});
 if(p.startsWith('/v1/admin/servers/')&&req.method==='PUT'){const input=await body();state.writes.push({p,input,csrf:req.headers['x-csrf-token']});if(state.serverError)return json(409,{code:state.serverError});const item=state.servers.find(s=>p.endsWith(s.id));if(input.expectedUpdatedAt!==item.updatedAt)return json(409,{code:'server_changed'});Object.assign(item,input,{updatedAt:future});return json(200,{updated:true});}
 if(p==='/v1/admin/members')return json(200,{members:[{id:subjectId,revision:'1',createdAt:future,administrator:false,studentId:'20991234',displayName:'합성 회원',department:'가상 학과',membershipStatus:'active',roleLabel:'회원',verifiedUntil:future,universityVerifiedUntil:future,allowedServerIds:['lobby','survival'],eligibleServerIds:['lobby','survival'],accessSuspended:false,scopeRestricted:false,scopeLimit:[],discordId:null,discordConnection:null,minecraft:{uuid:subjectId,name:'SyntheticPlayer'}}],total:1,nextCursor:null});
 if(p==='/v1/admin/service-credentials'){
  if(req.method==='POST'){const input=await body();state.credentialWrites.push({input,csrf:req.headers['x-csrf-token']});const credential={...input,id:'00000000-0000-4000-8000-000000000099',createdAt:future,revokedAt:null};state.credentials.push(credential);return json(201,{credential,token:'synthetic-single-view-secret'});}
  return json(200,{credentials:state.credentials,legacyEnabled:false});
 }
 if(p.startsWith('/v1/admin/service-credentials/')&&req.method==='DELETE'){state.credentialWrites.push({method:'DELETE',csrf:req.headers['x-csrf-token']});state.credentials[0].revokedAt=future;return json(200,{revoked:true});}
 if(p==='/v1/admin/observability'){const op={total:10,success:8,rejected:1,failure:1,codes:{timeout:1,ok:8,rejected:1},duration:{count:10,sumMs:1000,maxMs:300,buckets:[1,2,3,4,0,0]},lastSuccessAt:future,lastFailureAt:future};return json(200,{window:'process',startedAt:future,observedAt:future,parserVersion:'synthetic-parser',operations:{university:op,roster_sync:op,policy:op,events:op},roster:{enabled:true,running:false,lastSuccessAt:future,lastError:null,fetchedAt:future,expiresAt:future,fresh:true}});}
 if(p==='/v1/admin/manual') {
  if(req.method==='PUT'){const input=await body();state.manualWrites.push({input,csrf:req.headers['x-csrf-token']});if(state.manualConflict)return json(409,{code:'manual_settings_changed'});state.manual={...input,configured:!!input.notionUrl,revision:state.manual.revision+1,updatedAt:future};}
  return json(200,state.manual);
 }
 if(p==='/v1/admin/stats/export'){state.exports.push({input:await body(),csrf:req.headers['x-csrf-token']});const send=()=>{res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="passport-statistics.xlsx"'});res.end(Buffer.from('PK-synthetic-download'));};if(state.holdExport){state.holdExport=false;state.releaseExport=send;}else send();return;}
 if(p==='/v1/admin/stats/reset/preview'){const input=await body();state.previews.push(input);return json(200,{...input,affectedSubjects:1,rows:state.cleared?0:2,totals:counters,expectedRevision:`revision-${state.revision}`,confirmation:'통계 초기화'});}
 if(p==='/v1/admin/stats/reset'){const input=await body();state.writes.push({p,input,csrf:req.headers['x-csrf-token']});if(state.resetError)return json(409,{code:state.resetError});if(input.expectedRevision!==`revision-${state.revision}`)return json(409,{code:'statistics_reset_changed'});state.cleared=true;state.revision++;return json(200,{reset:true,affectedSubjects:1,rows:2});}
 if(p==='/v1/admin/stats'||p===`/v1/admin/members/${subjectId}/stats`){
  state.queries.push(Object.fromEntries(url.searchParams));state.queryPaths.push(p);
  const memberOnly=url.searchParams.get('membership')==='active';
  const totals=state.cleared?Object.fromEntries(Object.keys(counters).map(k=>[k,0])):state.membershipFixtures?{...counters,playSeconds:memberOnly?60:180,blocksBroken:memberOnly?10:30}:counters;
  const servers=state.servers.map(s=>({serverId:s.id,label:s.label,collectionEnabled:s.statisticsEnabled,firstCollectedAt:future,lastCollectedAt:future,...totals,onlinePlayerCount:s.id==='lobby'?1:0,...(state.membershipFixtures?{playSeconds:memberOnly?30:s.id==='survival'?120:60,blocksBroken:memberOnly?5:s.id==='survival'?20:10,onlinePlayerCount:memberOnly?1:2}:{})}));
  const response={available:true,firstCollectedAt:future,lastCollectedAt:future,period:{from:url.searchParams.get('from'),to:url.searchParams.get('to'),availableFrom:future,timezone:'Asia/Seoul',basis:'receivedAt'},daily:state.membershipFixtures?servers.filter(s=>s.collectionEnabled).map(s=>({...s,date:'2026-10-02'})):[{date:'2026-10-02',serverId:'survival',...totals}],totals,servers,collection:{enabled:p==='/v1/admin/stats'?null:false,effective:p==='/v1/admin/stats'?null:false,consentGranted:p==='/v1/admin/stats'?null:true,excludedServerIds:state.servers.filter(s=>!s.statisticsEnabled).map(s=>s.id),historyRetained:true},playerCount:state.membershipFixtures?(memberOnly?1:2):1,onlinePlayerCount:state.membershipFixtures?(memberOnly?1:2):1};
  if(state.holdStats){state.holdStats=false;state.releaseStats=()=>json(200,response);return;}
  return json(200,response);
 }
 const requested=path.resolve(dist,`.${p==='/'?'/index.html':p}`);if(!requested.startsWith(dist))return json(404,{});
 try{const data=await readFile(requested);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.woff2':'font/woff2'}[path.extname(requested)]||'application/octet-stream','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'"});res.end(data);}catch{json(404,{});}
});
const browser=async(...args)=>(await run(process.env.PASSPORT_AGENT_BROWSER||'npx',[...(process.env.PASSPORT_AGENT_BROWSER?[]:['--yes','agent-browser@0.38.1']),'--session',session,...args],{timeout:30000,maxBuffer:1e6})).stdout.trim();
const inspect=async expr=>{let value=JSON.parse(await browser('eval',`JSON.stringify(${expr})`));if(typeof value==='string')value=JSON.parse(value);return value;};
const until=async expr=>{for(let n=0;n<20;n++){if(await inspect(expr))return;await new Promise(r=>setTimeout(r,250));}assert.fail(expr);};
const click=name=>browser('find','role','button','click','--name',name,'--exact');
const open=async origin=>{await browser('open','about:blank');await browser('open',origin);await browser('wait','--load','networkidle');};
const stats=async origin=>{await open(origin);await click('플레이 통계');await until('document.querySelectorAll(".stats-metric").length===8');};
const confirm=async()=>{await browser('fill','#statistics-reset-confirmation','통계 초기화');await browser('find','role','checkbox','check','--name','초기화 범위와 삭제할 기록을 확인했습니다.');await click('기록 초기화');};
test('statistics collection and reset controls respect scope, retained history, revisions and roles',{timeout:300000},async t=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 const scenario=(name,run)=>t.test(name,{skip:!!process.env.PASSPORT_BROWSER_CASE&&!name.includes(process.env.PASSPORT_BROWSER_CASE)},run);
 try{
  await scenario('server command edit preserves internal ID and selected members while saving normalized alias and separate label',async()=>{
   reset();state.servers[0].accessMode='selected';state.servers[0].allowedSubjectIds=[subjectId,'00000000-0000-4000-8000-000000000099'];await open(origin);await click('서버 관리');await until('document.querySelectorAll(".server-summary").length===2');
   assert.equal(await inspect('document.querySelector(".server-summary-name strong").textContent'),'합성 로비');assert.equal(await inspect('document.querySelector(".server-command").textContent'),'/서버 로비');
   await browser('click','.server-summary');await click('접근 및 설정');await until('Boolean(document.querySelector("#server-command-name"))');
   assert.equal(await inspect('document.querySelector(".admin-dialog").textContent.includes("사용자도 본인 수집")'),false);assert.equal(await inspect('document.querySelector(".admin-dialog").textContent.includes("내부 ID: lobby")'),true);
   await browser('fill','#server-label','합성 약탈 월드');await browser('fill','#server-command-name','약탈'.normalize('NFD'));await until('document.querySelector(".server-command-preview code").textContent==="/서버 약탈"');
   await mkdir(output,{recursive:true});await browser('set','viewport','1440','1000');await browser('screenshot',path.join(output,'server-command-desktop.png'));await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot',path.join(output,'server-command-mobile.png'));
   await click('설정 저장');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.writes.length,1);
   assert.deepEqual(state.writes[0],{p:'/v1/admin/servers/lobby',input:{label:'합성 약탈 월드',commandName:'약탈',enabled:true,sensitive:false,accessMode:'selected',discordRequirement:'any',statisticsEnabled:false,allowedSubjectIds:[subjectId,'00000000-0000-4000-8000-000000000099'],expectedUpdatedAt:'2026-10-02T00:00:00.000Z'},csrf:'synthetic-csrf'});
   assert.equal(state.servers[0].id,'lobby');assert.equal(await inspect('document.querySelector(".server-summary-name strong").textContent'),'합성 약탈 월드');assert.equal(await inspect('document.querySelector(".server-command").textContent'),'/서버 약탈');assert.equal(state.cleared,false);
  });
  await scenario('server command validation blocks ambiguous input and local collisions then surfaces authoritative conflicts without changing ID',async()=>{
   reset();await open(origin);await click('서버 관리');await until('Boolean(document.querySelector(".server-summary"))');await browser('click','.server-summary');await click('접근 및 설정');await until('Boolean(document.querySelector("#server-command-name"))');
   for(const value of ['', '약 탈', ' 약탈', 'a'.repeat(65), 'SURVIVAL', '야생']) {
    if(value)await browser('fill','#server-command-name',value);else await browser('eval',`(() => { const input=document.querySelector('#server-command-name'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,''); input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
    await click('설정 저장');await until('Boolean(document.querySelector("#server-command-error"))');assert.equal(await inspect('document.querySelector("#server-command-name").getAttribute("aria-invalid")'),'true');assert.equal(state.writes.length,0);
   }
   await browser('fill','#server-command-name','RAID_2');assert.equal(await inspect('document.querySelector("#server-command-error")===null'),true);assert.equal(await inspect('document.querySelector(".server-command-preview code").textContent'),'/서버 raid_2');
   state.serverError='server_command_conflict';await click('설정 저장');await until('document.querySelector("#server-command-error")?.textContent.includes("다른 서버")');assert.equal(state.writes.length,1);assert.equal(state.servers[0].commandName,'로비');assert.equal(state.writes[0].input.commandName,'raid_2');
   state.serverError='server_changed';await browser('fill','#server-command-name','Raid_3');await click('설정 저장');await until('document.querySelector(".admin-dialog").textContent.includes("다른 곳에서 서버 설정이 변경되었습니다")');assert.equal(state.servers[0].commandName,'로비');assert.equal(state.writes[1].input.expectedUpdatedAt,'2026-10-02T00:00:00.000Z');await click('취소');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.servers[0].id,'lobby');
  });
  await scenario('server command remains visible to viewers but writes disappear after a live permission downgrade',async()=>{
   reset();state.role='viewer';await open(origin);await click('서버 관리');await until('Boolean(document.querySelector(".server-summary"))');assert.equal(await inspect('document.querySelector(".server-command").textContent'),'/서버 로비');await browser('click','.server-summary');assert.equal(await inspect('document.querySelector(".server-expanded button")===null'),true);assert.equal(state.writes.length,0);
   reset();await open(origin);await click('서버 관리');await until('Boolean(document.querySelector(".server-summary"))');await browser('click','.server-summary');await click('접근 및 설정');await until('Boolean(document.querySelector("#server-command-name"))');await browser('fill','#server-command-name','약탈');state.role='viewer';await browser('eval','window.dispatchEvent(new Event("focus"))');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.writes.length,0);assert.equal(state.servers[0].commandName,'로비');assert.equal(await inspect('localStorage.length+sessionStorage.length'),0);assert.equal(await browser('errors'),'');
  });
  await scenario('server command missing in an older API remains read-only while ordinary settings save without the new field',async()=>{
   reset();delete state.servers[0].commandName;await open(origin);await click('서버 관리');await until('Boolean(document.querySelector(".server-summary"))');assert.equal(await inspect('document.querySelector(".server-command").textContent'),'/서버 lobby');
   await browser('click','.server-summary');await click('접근 및 설정');await until('Boolean(document.querySelector("#server-command-name"))');assert.equal(await inspect('document.querySelector("#server-command-name").disabled'),true);assert.equal(await inspect('document.querySelector("#server-command-name").value'),'lobby');assert.match(await inspect('document.querySelector("#server-command-help").textContent'),/준비 중/);
   await browser('fill','#server-label','이전 서버 이름 수정');await click('설정 저장');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.writes.length,1);assert.equal('commandName' in state.writes[0].input,false);assert.equal(state.writes[0].input.label,'이전 서버 이름 수정');assert.equal(state.writes[0].csrf,'synthetic-csrf');assert.equal(state.writes[0].input.expectedUpdatedAt,'2026-10-02T00:00:00.000Z');assert.equal(state.servers[0].id,'lobby');assert.equal(await inspect('document.querySelector(".server-command").textContent'),'/서버 lobby');assert.equal(await browser('errors'),'');
  });
  await scenario('server toggle displays lobby OFF, confirms collection impact, sends revision and preserves stored history',async()=>{
   reset();await open(origin);await click('서버 관리');await until('document.querySelectorAll(".server-summary").length===2');await browser('click','.server-summary');assert.equal(await inspect('document.querySelector(".server-expanded").textContent.includes("꺼짐 · 합계 제외")'),true);await click('접근 및 설정');await until('Boolean(document.querySelector(".server-statistics-setting"))');assert.equal(await inspect('document.querySelector(".server-statistics-setting input").checked'),false);
   await browser('find','role','checkbox','check','--name','이 서버 통계 수집');await browser('set','viewport','1440','900');await mkdir(output,{recursive:true});await browser('screenshot',path.join(output,'statistics-server-settings-desktop.png'));
   state.serverError='server_changed';await click('설정 저장');await until('document.body.textContent.includes("다른 곳에서 서버 설정이 변경되었습니다")');assert.equal(state.servers[0].statisticsEnabled,false);state.serverError=null;await click('설정 저장');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.servers[0].statisticsEnabled,true);assert.equal(state.writes.at(-1).input.expectedUpdatedAt,'2026-10-02T00:00:00.000Z');assert.equal(state.writes.at(-1).csrf,'synthetic-csrf');assert.equal(state.cleared,false);
  });
  await scenario('excluded server is absent; enabled server reset previews data and rejects stale generation',async()=>{
   reset();await stats(origin);assert.equal(await inspect('document.querySelectorAll(".metric-icon").length'),8);assert.deepEqual(await inspect('[...document.querySelector(".stats-scope select").options].map(option=>option.value)'),['','survival']);await browser('select','.stats-scope select','survival');assert.equal(await inspect('document.querySelectorAll(".stats-metric").length'),8);
   await click('이 서버 통계 초기화');await until('Boolean(document.querySelector("#statistics-reset-confirmation"))');assert.deepEqual(state.previews.at(-1),{scope:'server',serverId:'survival'});assert.equal(await inspect('document.querySelector(".dialog-actions .primary").disabled'),true);assert.equal(state.writes.length,0);assert.equal(await inspect('document.querySelector(".stats-reset-target").textContent.includes("합성 야생")'),true);
   await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-statistics-reset-mobile.png','--full');
   state.revision++;await confirm();await until('document.body.textContent.includes("초기화 대상의 연결 또는 기록 상태가 변경되었습니다")');assert.equal(await inspect('document.querySelector("#statistics-reset-confirmation")===null'),true);assert.equal(state.cleared,false);await click('영향 다시 확인');await until('Boolean(document.querySelector("#statistics-reset-confirmation"))');assert.equal(await inspect('document.querySelector("#statistics-reset-confirmation").value'),'');assert.equal(await inspect('document.querySelector(".admin-dialog input[type=checkbox]").checked'),false);await confirm();await until('document.querySelector(".admin-dialog")===null');assert.equal(state.cleared,true);assert.deepEqual(state.writes.at(-1).input,{scope:'server',serverId:'survival',expectedRevision:'revision-2',confirmation:'통계 초기화'});
  });
  await scenario('all and personal reset scope is explicit and cancel never changes records',async()=>{
   reset();await stats(origin);await click('전체 통계 초기화');await until('Boolean(document.querySelector("#statistics-reset-confirmation"))');assert.deepEqual(state.previews.at(-1),{scope:'all'});await browser('press','Escape');await until('document.querySelector(".admin-dialog")===null');assert.equal(state.writes.length,0);
   await click('회원 관리');await until('Boolean(document.querySelector(".member-summary"))');await browser('click','.member-summary');await click('플레이 기록');await until('document.querySelectorAll(".member-stats .stats-metric").length===8');await browser('select','.member-stats .stats-scope select','survival');await click('이 회원 전체 통계 초기화');await until('Boolean(document.querySelector("#statistics-reset-confirmation"))');assert.deepEqual(state.previews.at(-1),{scope:'subject',subjectId});assert.equal(await inspect('document.querySelector(".stats-reset-target").textContent.includes("이 회원의 모든 서버 기록")'),true);await click('취소');assert.equal(state.writes.length,0);
  });
  await scenario('administrator export carries selected server and period; daily history is visible',async()=>{
   reset();await stats(origin);await browser('select','.stats-scope select','survival');await browser('eval',`(() => { const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set; [...document.querySelectorAll('.stats-period input')].forEach((input, i) => { setter.call(input, ['2026-10-01','2026-10-02'][i]); input.dispatchEvent(new Event('input', {bubbles:true})); input.dispatchEvent(new Event('change', {bubbles:true})); }); })()`);assert.deepEqual(await inspect('[...document.querySelectorAll(".stats-period input")].map(input=>input.value)'),['2026-10-01','2026-10-02']);await click('기간 조회');await until('document.querySelector(".stats-history-note")?.textContent.includes("2026-10-01 ~ 2026-10-02")');assert.deepEqual(state.queries.at(-1),{from:'2026-10-01',to:'2026-10-02',membership:'all'});
   assert.equal(await inspect('document.querySelector(".stats-collected").textContent.includes("최초 수집")'),true);assert.equal(await inspect('document.querySelectorAll(".chart-point").length'),1);assert.equal(await inspect('document.body.textContent.includes("AFK")'),false);await click('엑셀 다운로드');await until('document.body.textContent.includes("엑셀 파일을 다운로드했습니다")');assert.deepEqual(state.exports[0],{input:{serverId:'survival',from:'2026-10-01',to:'2026-10-02',membership:'all'},csrf:'synthetic-csrf'});
   await browser('set','viewport','1440','900');await browser('screenshot','/tmp/passport-stats-admin-history-desktop.png','--full');await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-stats-admin-history-mobile.png','--full');
  });
  await scenario('membership filter updates totals, daily history and counts with period/server export scope locked',async()=>{
   reset();state.membershipFixtures=true;state.servers.push(serverRecord('build','합성 건축',true));await stats(origin);
   assert.equal(await inspect('document.querySelector("#statistics-membership").value'),'all');assert.deepEqual(state.queries.at(-1),{membership:'all'});assert.equal(await inspect('document.querySelector(".stats-metric strong").textContent'),'3분');assert.match(await inspect('document.querySelector(".stats-toolbar p").textContent'),/플레이어 2명/);
   await browser('select','#statistics-membership','active');await until('document.querySelector(".stats-metric strong")?.textContent==="1분"');assert.deepEqual(state.queries.at(-1),{membership:'active'});assert.match(await inspect('document.querySelector(".stats-toolbar p").textContent'),/플레이어 1명/);assert.equal(await inspect('document.querySelector(".stats-reset-actions")===null'),true);assert.equal(await inspect('document.querySelector(".stats-reset-filter-note").textContent'),'전체 사용자 보기에서 통계를 초기화할 수 있습니다.');
   await browser('select','.stats-scope select','survival');assert.equal(await inspect('document.querySelector(".stats-metric strong").textContent'),'30초');assert.equal(await inspect('document.querySelector(".stats-presence strong").textContent'),'현재 접속 1명');await browser('click','.stats-history summary');assert.equal(await inspect('document.querySelector(".stats-daily-table tbody td").textContent'),'30초');
   await browser('eval',`(() => { const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; [...document.querySelectorAll('.stats-period input')].forEach((input,i)=>{setter.call(input,['2026-10-01','2026-10-02'][i]);input.dispatchEvent(new Event('input',{bubbles:true}));}); })()`);await click('기간 조회');await until('document.querySelector(".stats-history-note")?.textContent.includes("2026-10-01 ~ 2026-10-02")');assert.deepEqual(state.queries.at(-1),{from:'2026-10-01',to:'2026-10-02',membership:'active'});assert.equal(await inspect('document.querySelector(".stats-scope select").value'),'survival');
   state.holdExport=true;await click('엑셀 다운로드');await until('document.querySelector("#statistics-membership").disabled');assert.equal(await inspect('document.querySelector(".stats-scope select").disabled'),true);assert.equal(await inspect('[...document.querySelectorAll(".stats-period input, .stats-period button")].every(element=>element.disabled)'),true);assert.deepEqual(state.exports.at(-1),{input:{serverId:'survival',from:'2026-10-01',to:'2026-10-02',membership:'active'},csrf:'synthetic-csrf'});state.releaseExport();state.releaseExport=null;await until('document.body.textContent.includes("엑셀 파일을 다운로드했습니다")');assert.equal(await inspect('document.querySelector("#statistics-membership").disabled'),false);
   await browser('set','viewport','1440','1000');await browser('screenshot','/tmp/passport-admin-membership-stats-desktop.png','--full');await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-admin-membership-stats-mobile.png','--full');
   await browser('select','#statistics-membership','all');await until('document.querySelector(".stats-metric strong")?.textContent==="2분"');assert.deepEqual(state.queries.at(-1),{from:'2026-10-01',to:'2026-10-02',membership:'all'});assert.equal(await inspect('document.querySelector(".stats-reset-actions button").textContent'),'이 서버 통계 초기화');assert.equal(state.previews.length,0);assert.equal(state.writes.length,0);
  });
  await scenario('membership stale response is discarded and individual member statistics remain unfiltered',async()=>{
   reset();state.membershipFixtures=true;await stats(origin);state.holdStats=true;await browser('select','#statistics-membership','active');await until('document.querySelector(".stats-view").getAttribute("aria-busy")==="true"');assert.equal(typeof state.releaseStats,'function');await browser('select','#statistics-membership','all');await until('document.querySelector(".stats-metric strong")?.textContent==="3분"');state.releaseStats();state.releaseStats=null;await browser('wait','--load','networkidle');assert.equal(await inspect('document.querySelector(".stats-metric strong").textContent'),'3분');assert.match(await inspect('document.querySelector(".stats-toolbar p").textContent'),/플레이어 2명/);
   await click('회원 관리');await until('Boolean(document.querySelector(".member-summary"))');await browser('click','.member-summary');await click('플레이 기록');await until('document.querySelectorAll(".member-stats .stats-metric").length===8');assert.equal(await inspect('document.querySelector("#statistics-membership")===null'),true);assert.equal(state.queryPaths.at(-1),`/v1/admin/members/${subjectId}/stats`);assert.deepEqual(state.queries.at(-1),{});assert.equal(await inspect('document.querySelector(".stats-reset-actions button").textContent'),'이 회원 전체 통계 초기화');await click('엑셀 다운로드');await until('document.body.textContent.includes("엑셀 파일을 다운로드했습니다")');assert.deepEqual(state.exports.at(-1).input,{subjectId});assert.equal(await inspect('localStorage.length+sessionStorage.length'),0);assert.equal(await browser('errors'),'');
  });
  await scenario('manual editor saves public URL with CSRF and revision; conflict blocks retry until reload',async()=>{
   reset();await open(origin);await click('매뉴얼 관리');await until('Boolean(document.querySelector("#manual-title"))');await browser('fill','#manual-title','오버월드 이용 안내');await browser('fill','#manual-url','https://example.notion.site/123456789012345678901234567890ab');await click('매뉴얼 저장');await until('document.body.textContent.includes("매뉴얼을 저장했습니다")');assert.deepEqual(state.manualWrites[0],{input:{title:'오버월드 이용 안내',notionUrl:'https://example.notion.site/123456789012345678901234567890ab',embedUrl:null,expectedRevision:0},csrf:'synthetic-csrf'});
   await browser('fill','#manual-embed','https://example.notion.site/ebd/123456789012345678901234567890ab');await browser('eval',`(() => { const input=document.querySelector('#manual-url'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,''); input.dispatchEvent(new Event('input',{bubbles:true})); input.dispatchEvent(new Event('change',{bubbles:true})); })()`);await click('매뉴얼 저장');await until('document.body.textContent.includes("매뉴얼 등록을 해제했습니다")');assert.equal(state.manualWrites.at(-1).input.embedUrl,null);assert.equal(state.manual.configured,false);state.manualConflict=true;await click('매뉴얼 저장');await until('document.body.textContent.includes("다른 운영자가 매뉴얼을 변경했습니다")');assert.equal(await inspect('document.querySelector("#manual-title").disabled'),true);state.manualConflict=false;await click('최신 설정 불러오기');await until('document.querySelector("#manual-title")?.disabled===false');await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-manual-admin-mobile.png','--full');
   reset();state.role='viewer';await open(origin);await click('매뉴얼 관리');await until('Boolean(document.querySelector("#manual-title"))');assert.equal(await inspect('document.querySelector("#manual-title").disabled'),true);assert.equal(await inspect('[...document.querySelectorAll("button")].some(button=>button.textContent==="매뉴얼 저장")'),false);assert.equal(state.manualWrites.length,0);
  });
  await scenario('manual editor accepts copied double-slash embeds and explains invalid fields before a request',async()=>{
   reset();await open(origin);await click('매뉴얼 관리');await until('Boolean(document.querySelector("#manual-url"))');
   const page='https://example.notion.site/123456789012345678901234567890ab',embed='https://example.notion.site/ebd//123456789012345678901234567890ab';
   await browser('fill','#manual-url',embed);await click('매뉴얼 저장');await until('Boolean(document.querySelector("#manual-url-error"))');assert.equal(state.manualWrites.length,0);assert.equal(await inspect('document.querySelector("#manual-url").getAttribute("aria-invalid")'),'true');
   await browser('fill','#manual-url',page);await browser('fill','#manual-embed','<iframe src="'+embed+'"></iframe>');await click('매뉴얼 저장');await until('document.querySelector("#manual-embed-error")?.textContent.includes("src 안의 HTTPS 주소만")');assert.equal(state.manualWrites.length,0);
   await browser('fill','#manual-embed','https://example.notion.site/ebd//aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');await click('매뉴얼 저장');await until('document.querySelector("#manual-embed-error")?.textContent.includes("같은 Notion 페이지")');assert.equal(state.manualWrites.length,0);
   await browser('fill','#manual-embed',embed);await click('매뉴얼 저장');await until('document.body.textContent.includes("매뉴얼을 저장했습니다")');assert.equal(state.manualWrites.length,1);assert.equal(state.manualWrites[0].input.embedUrl,embed);assert.equal(state.manualWrites[0].csrf,'synthetic-csrf');assert.equal(await inspect('document.querySelector("#manual-embed-error")===null'),true);
  });
  await scenario('status view separates processing outcomes and marks restart window',async()=>{
   reset();await open(origin);await click('상태 감시');await until('document.querySelectorAll(".observability-operation").length===4');assert.equal(await inspect('document.body.textContent.includes("재시작하면 집계가 새로 시작됩니다")'),true);assert.equal(await inspect('document.querySelectorAll(".observability-counts .error-text").length'),4);await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-observability-mobile.png','--full');
  });
  await scenario('owner issues scoped key once and revokes only after explicit confirmation; operators have no key menu',async()=>{
   reset();await open(origin);await click('서비스 연결 키');await until('document.body.textContent.includes("등록된 연결 키가 없습니다")');await click('새 키 발급');await browser('fill','#credential-service','paper-synthetic');await browser('select','#credential-server','survival');await click('연결 키 발급');await until('Boolean(document.querySelector("#issued-service-key"))');assert.equal(await inspect('document.querySelector("#issued-service-key").value'),'synthetic-single-view-secret');assert.equal(await inspect('document.querySelector("#issued-service-key").type'),'password');assert.equal(await inspect('localStorage.length+sessionStorage.length'),0);
   assert.equal(state.credentialWrites[0].csrf,'synthetic-csrf');assert.equal(state.credentialWrites[0].input.audience,'minecraft');assert.deepEqual(state.credentialWrites[0].input.serverIds,['survival']);assert.equal(state.credentialWrites[0].input.scopes.includes('game:stats:write'),true);assert.equal(state.credentialWrites[0].input.scopes.includes('game:link'),false);
   await click('상태 감시');await until('document.querySelectorAll(".observability-operation").length===4');await click('서비스 연결 키');await until('Boolean(document.querySelector(".credential-item"))');assert.equal(await inspect('document.querySelector("#issued-service-key")===null'),true);await browser('click','.credential-item summary');await click('연결 키 회수');assert.equal(await inspect('document.querySelector(".dialog-actions .primary").disabled'),true);await click('취소');assert.equal(state.credentialWrites.length,1);await click('연결 키 회수');await browser('find','role','checkbox','check','--name','대상 서비스와 연결 중단 영향을 확인했습니다.');await click('회수 확인');await until('document.body.textContent.includes("이후 요청부터 사용할 수 없습니다")');assert.deepEqual(state.credentialWrites[1],{method:'DELETE',csrf:'synthetic-csrf'});
   await browser('set','viewport','390','844');assert.equal(await inspect('document.documentElement.scrollWidth<=innerWidth'),true);await browser('screenshot','/tmp/passport-service-keys-mobile.png','--full');state.role='operator';await open(origin);assert.equal(await inspect('[...document.querySelectorAll("nav button")].some(button=>button.textContent.includes("서비스 연결 키"))'),false);
  });
  await scenario('viewer cannot toggle or reset and a live role downgrade closes pending reset',async()=>{
   reset();state.role='viewer';await stats(origin);assert.equal(await inspect('document.querySelector(".stats-reset-actions")===null'),true);assert.equal(await inspect('[...document.querySelectorAll("button")].some(button=>button.textContent==="엑셀 다운로드")'),false);await click('서버 관리');await until('Boolean(document.querySelector(".server-summary"))');await browser('click','.server-summary');assert.equal(await inspect('document.querySelector(".server-expanded button")===null'),true);assert.equal(state.writes.length,0);
   reset();await stats(origin);await click('전체 통계 초기화');await until('Boolean(document.querySelector("#statistics-reset-confirmation"))');state.role='viewer';await browser('eval','window.dispatchEvent(new Event("focus"))');await until('document.querySelector(".admin-dialog")===null');assert.equal(await inspect('document.querySelector(".stats-reset-actions")===null'),true);assert.equal(state.writes.length,0);assert.equal(await inspect('localStorage.length+sessionStorage.length'),0);assert.equal(await browser('errors'),'');
  });
 }finally{state.releaseStats?.();state.releaseExport?.();await browser('close').catch(()=>{});await new Promise(r=>server.close(r));}
});
