import { useEffect, useEffectEvent, useState } from "react";
import { api, errorMessage } from "./api";
import { number } from "./statistics";
import { dateTime } from "./types";
import type { ReportError } from "./types";
interface Operation { total: number; success: number; rejected: number; failure: number; codes: Record<string, number>; duration: { count: number; sumMs: number; maxMs: number; buckets: number[] }; lastSuccessAt: string | null; lastFailureAt: string | null }
interface Observability { window: "process"; startedAt: string; observedAt: string; parserVersion: string; operations: Record<"university" | "roster_sync" | "policy" | "events", Operation>; roster: { enabled: boolean; running: boolean; lastSuccessAt: string | null; lastError: string | null; fetchedAt: string | null; expiresAt: string | null; fresh: boolean } }
const labels = { university: "학교 인증", roster_sync: "회원 시트 동기화", policy: "접근 정책", events: "정책 변경 전송" };
export function ObservabilityView({ onError }: { onError: ReportError }) {
  const [data, setData] = useState<Observability | null>(null);
  const [error, setError] = useState("");
  const [refresh, setRefresh] = useState(0);
  const failed = useEffectEvent((failure: unknown) => { setError(errorMessage(failure)); onError(failure); });
  useEffect(() => { const controller = new AbortController(); setData(null); setError(""); void api<Observability>("/admin/observability", { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setData(value); }).catch(failure => { if (!controller.signal.aborted) failed(failure); }); return () => controller.abort(); }, [refresh]);
  return <section aria-label="서비스 상태 감시"><div className="stats-toolbar"><div><h2>중앙 API 상태</h2><p>API가 시작된 이후의 처리 결과입니다. 재시작하면 집계가 새로 시작됩니다.</p></div><button onClick={() => setRefresh(value => value + 1)}>상태 새로고침</button></div>{error ? <p className="notice notice-error" role="alert">{error}</p> : !data ? <p role="status">상태를 불러오는 중입니다.</p> : <><div className="observability-meta"><span>시작 {dateTime(data.startedAt)}</span><span>확인 {dateTime(data.observedAt)}</span><span>파서 {data.parserVersion}</span></div><div className="observability-grid">{(Object.keys(labels) as (keyof typeof labels)[]).map(key => { const op = data.operations[key]; return <section className="panel observability-operation" key={key}><div className="panel-head"><h3>{labels[key]}</h3><span>{number(op.total)}건</span></div><dl className="observability-counts"><div><dt>성공</dt><dd>{number(op.success)}</dd></div><div><dt>거절</dt><dd>{number(op.rejected)}</dd></div><div><dt>실패</dt><dd className={op.failure ? "error-text" : undefined}>{number(op.failure)}</dd></div></dl><dl className="detail-list"><div><dt>최근 성공</dt><dd>{dateTime(op.lastSuccessAt)}</dd></div><div><dt>최근 실패</dt><dd>{dateTime(op.lastFailureAt)}</dd></div><div><dt>평균 처리 시간</dt><dd>{number(op.duration.count ? op.duration.sumMs / op.duration.count : 0)} ms</dd></div><div><dt>최대 처리 시간</dt><dd>{number(op.duration.maxMs)} ms</dd></div></dl>{Object.keys(op.codes).length ? <details><summary>결과 코드</summary><ul className="observability-codes">{Object.entries(op.codes).map(([code, count]) => <li key={code}><code>{code}</code><span>{number(count)}건</span></li>)}</ul></details> : null}</section>; })}</div><section className="panel observability-roster"><div className="panel-head"><h3>회원 명부</h3><span className={data.roster.fresh ? "status-label" : "error-text"}>{data.roster.fresh ? "최신 명부 적용 중" : "명부 상태 확인 필요"}</span></div><dl className="detail-list"><div><dt>자동 동기화</dt><dd>{data.roster.running ? "진행 중" : data.roster.enabled ? "켜짐" : "꺼짐"}</dd></div><div><dt>최근 성공</dt><dd>{dateTime(data.roster.lastSuccessAt)}</dd></div><div><dt>유효기간</dt><dd>{dateTime(data.roster.expiresAt)}</dd></div></dl>{data.roster.lastError ? <p className="error-text">최근 동기화에 실패했습니다. 회원 시트 동기화에서 상태를 확인해 주세요.</p> : null}</section></>}</section>;
}
